### ISSUE TITLE
command 'extension.translateOnHoverEnable' not found

### ISSUE THREAD

**Issue by rainjm** [voldikss/vscode-translator#2]
执行命令都是弹出找不到

**Comment by voldikss** [comment]
emmm 是在 Windows 下吗

**Comment by rainjm** [comment]
macOS

**Comment by voldikss** [comment]
emmm 当时只在 linux 下弄过可以，Windows 下我也会报错。先不要用这个了，我有空修一下 :neckbeard:

**Comment by voldikss** [comment]
你好，刚刚发现之前的版本没传对，刚刚上传了新版本，我这边 Windows 上正常工作了。能帮忙测试下 mac OS 上的情况吗

**Comment by rainjm** [comment]
更新之后可以了，但我发现Comment Translate更好用，只是设置选项较少；单词没有音标，只有一个中文译词。

**Comment by voldikss** [comment]
嗯嗯好的。Comment Translate 我也用，很好用。
